import { FormEvent, useEffect, useState } from "react";
import { Announcement, approveStatus, createSchedule, loadAdminStatusDashboard, loadAnnouncements, loadSchedules, publishAnnouncement, publishSchedule, StatusDashboard, withdrawAnnouncement, WorkSchedule } from "../shared/api/client";

export function OperationsAdminPanel({moduleCode,onClose}:{moduleCode:string;onClose:()=>void}){
  const titles:Record<string,string>={announcements:"公告管理",schedules:"班务与值班",status_requests:"状态申请"};
  return <section className="governance-panel operations-panel"><header className="governance-header"><div><span className="eyebrow">OPERATIONS</span><h2>{titles[moduleCode]}</h2></div><button className="text-button" onClick={onClose}>返回总览</button></header>{moduleCode==="announcements"?<Announcements/>:moduleCode==="schedules"?<Schedules/>:<Statuses/>}</section>;
}

function Announcements(){
  const [items,setItems]=useState<Announcement[]>([]);const [title,setTitle]=useState("");const [content,setContent]=useState("");const [message,setMessage]=useState("");const [pinned,setPinned]=useState(false);const [publishAt,setPublishAt]=useState("");const [images,setImages]=useState<Array<{filename:string;mimeType:string;base64Data:string}>>([]);
  const refresh=()=>loadAnnouncements(true).then(r=>setItems(r.items)).catch(e=>setMessage(e.message));useEffect(()=>{void refresh()},[]);
  async function chooseImages(files:FileList|null){if(!files)return;if(files.length>5){setMessage("每条公告最多 5 张图片");return}const encoded=await Promise.all(Array.from(files).map(async file=>({filename:file.name,mimeType:file.type,base64Data:await readFile(file)})));setImages(encoded)}
  async function submit(event:FormEvent){event.preventDefault();await publishAnnouncement({title,content,contentFormat:"basic_rich_text",pinned,publishAt:publishAt?new Date(publishAt).toISOString():undefined,images});setTitle("");setContent("");setImages([]);setMessage("公告已保存");refresh();}
  async function withdraw(id:number){await withdrawAnnouncement(id);setMessage("公告已撤回");refresh()}
  return <div className="governance-grid"><div><div className="panel-metric"><strong>{items.length}</strong><span>最近公告</span></div><div className="operations-list">{items.map(item=><article key={item.id}><span className={`state state-${item.publicationStatus}`}>{item.publicationStatus}{item.pinned?" · 置顶":""}</span><h3>{item.title}</h3><p>{item.content}</p>{item.images?.length>0&&<small>{item.images.length} 张图片</small>}{item.publicationStatus!=="withdrawn"&&<button className="text-button" onClick={()=>void withdraw(item.id)}>撤回</button>}</article>)}</div></div><form className="knowledge-form" onSubmit={submit}><h3>发布公告</h3><label>标题<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>正文<textarea required value={content} onChange={e=>setContent(e.target.value)}/></label><label>预约生效<input type="datetime-local" value={publishAt} onChange={e=>setPublishAt(e.target.value)}/></label><label className="inline-check"><input type="checkbox" checked={pinned} onChange={e=>setPinned(e.target.checked)}/>置顶公告</label><label>公告图片（最多 5 张）<input type="file" accept="image/png,image/jpeg" multiple onChange={e=>void chooseImages(e.target.files)}/></label><small>已选择 {images.length} 张</small><button type="submit">保存公告</button><output>{message}</output></form></div>;
}
function readFile(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)})}
function Schedules(){
  const [items,setItems]=useState<WorkSchedule[]>([]);const [week,setWeek]=useState("");const [message,setMessage]=useState("");const refresh=()=>loadSchedules().then(setItems).catch(e=>setMessage(e.message));useEffect(()=>{void refresh()},[]);
  async function submit(event:FormEvent){event.preventDefault();await createSchedule(week);setMessage("周排班已创建");refresh();}
  async function publish(id:number){await publishSchedule(id);setMessage("周排班已发布");refresh()}
  return <div className="governance-grid"><div className="operations-list">{items.map(item=><article key={item.id}><span className="state">{item.scheduleStatus}</span><h3>{item.weekStart}</h3><p>支持多人早晚班、复制周计划和代班。</p>{item.scheduleStatus==="draft"&&<button className="text-button" onClick={()=>void publish(item.id)}>发布排班</button>}</article>)}</div><form className="knowledge-form" onSubmit={submit}><h3>新建周排班</h3><label>周一日期<input required type="date" value={week} onChange={e=>setWeek(e.target.value)}/></label><button type="submit">创建</button><output>{message}</output></form></div>;
}
function Statuses(){
  const [data,setData]=useState<StatusDashboard|null>(null);const [message,setMessage]=useState("");const refresh=()=>loadAdminStatusDashboard().then(setData).catch(e=>setMessage(e.message));useEffect(()=>{refresh();const id=window.setInterval(refresh,5000);return()=>window.clearInterval(id)},[]);
  async function approve(id:number,over=false){await approveStatus(id,over,over?"管理员超额批准":"批准申请");refresh();}
  if(!data)return <p role="status">{message||"正在加载状态…"}</p>;
  return <><div className="metrics-strip"><span><strong>{data.metrics.shortBreakWaiting}</strong>小休排队</span><span><strong>{data.metrics.longBreakWaiting}</strong>大休排队</span><span><strong>{data.metrics.active}</strong>进行中</span><span><strong>{data.metrics.overtime}</strong>超时提醒</span></div><div className="queue-columns"><Queue title="小休队列" items={data.shortBreakQueue}/><Queue title="大休队列" items={data.longBreakQueue}/><section><h3>待处理 / 进行中</h3>{data.requests.map(item=><div className="queue-row" key={item.id}><span>{item.employeeName}<small>{item.displayName} · {item.requestStatus}</small></span>{item.requestStatus==="pending"&&<span><button onClick={()=>approve(item.id)}>批准</button><button onClick={()=>approve(item.id,true)}>超额批准</button></span>}</div>)}</section></div></>;
}
function Queue({title,items}:{title:string;items:StatusDashboard["shortBreakQueue"]}){return <section><h3>{title}</h3>{items.length===0?<p className="empty-copy">当前无人排队</p>:items.map(item=><div className="queue-row" key={item.id}><strong>{item.position}</strong><span>{item.employeeName}<small>{item.requestedDurationMinutes} 分钟</small></span></div>)}</section>}
